package com.lojasocial.app.data.api

import retrofit2.Response
import retrofit2.http.Body
import retrofit2.http.Header
import retrofit2.http.POST

/**
 * Data class representing a chat request to the AI API.
 * 
 * @param model The AI model to use for generating responses. Defaults to "xiaomi/mimo-v2-flash:free".
 * @param messages A list of chat messages representing the conversation history.
 */
data class ChatRequest(
    val model: String = "xiaomi/mimo-v2-flash:free",
    val messages: List<ChatMessageRequest>
)

/**
 * Data class representing a single message in the chat conversation.
 * 
 * @param role The role of the message sender ("user" or "assistant").
 * @param content The text content of the message.
 */
data class ChatMessageRequest(
    val role: String,
    val content: String
)

/**
 * Data class representing the response from the chat API.
 * 
 * @param choices A list of possible responses from the AI model.
 */
data class ChatResponse(
    val choices: List<ChatChoice>
)

/**
 * Data class representing a choice in the API response.
 * 
 * @param message The message content generated by the AI.
 */
data class ChatChoice(
    val message: ChatMessageResponse
)

/**
 * Data class representing the message response from the AI.
 * 
 * @param role The role of the message sender (should be "assistant").
 * @param content The generated text content.
 */
data class ChatMessageResponse(
    val role: String,
    val content: String
)

/**
 * Retrofit interface for the Chat API service.
 * 
 * This interface defines the HTTP endpoints for communicating with the
 * Loja Social chat API hosted at https://lojasocial-ipca.onrender.com/
 * 
 * The API uses POST requests with JSON payloads and requires Bearer token
 * authentication for authorization.
 */
interface ChatApiService {
    /**
     * Sends a chat message to the AI API and returns the response.
     * 
     * @param authorization The Bearer token for API authentication (format: "Bearer lojasocial2025").
     * @param contentType The content type of the request (should be "application/json").
     * @param request The chat request containing the model and messages.
     * @return Response containing the AI-generated message or error information.
     */
    @POST("api/chat")
    suspend fun sendMessage(
        @Header("Authorization") authorization: String,
        @Header("Content-Type") contentType: String,
        @Body request: ChatRequest
    ): Response<ChatResponse>
}
