package com.lojasocial.app.data.model

import android.net.Uri
import java.util.Date

/**
 * Represents a complete scholarship application submitted by a student.
 * 
 * This data class contains all the information required for a scholarship application,
 * including personal details, academic information, supporting documents, and metadata
 * about the submission process.
 * 
 * @property id Unique identifier for the application (generated by Firestore)
 * @property userId Unique identifier of the user who submitted the application
 * @property personalInfo Personal information of the applicant
 * @property academicInfo Academic details and support information
 * @property documents List of supporting documents required for the application
 * @property submissionDate Date when the application was submitted
 * @property status Current status of the application in the review process
 * 
 * @see PersonalInfo Personal information data class
 * @see AcademicInfo Academic information data class
 * @see ApplicationDocument Document attachment data class
 * @see ApplicationStatus Application status enumeration
 */
data class Application(
    val id: String = "",
    val userId: String = "",
    val personalInfo: PersonalInfo,
    val academicInfo: AcademicInfo,
    val documents: List<ApplicationDocument>,
    val submissionDate: Date = Date(),
    val status: ApplicationStatus = ApplicationStatus.PENDING,
    val rejectionMessage: String? = null // Message from employee when rejecting the application
)

/**
 * Contains personal information of the scholarship applicant.
 * 
 * This data class stores all the personal details required for identity verification
 * and contact purposes during the application process.
 * 
 * @property name Full name of the applicant
 * @property dateOfBirth Date of birth (nullable for cases where it might not be provided)
 * @property idPassport ID card or passport number for identification
 * @property email Email address for communication
 * @property phone Phone number for contact
 */
data class PersonalInfo(
    val name: String,
    val dateOfBirth: Date?,
    val idPassport: String,
    val email: String,
    val phone: String
)

/**
 * Contains academic information and support details of the applicant.
 * 
 * This data class stores information about the applicant's academic pursuits,
 * including their degree program, student identification, and financial support status.
 * 
 * @property academicDegree The academic degree being pursued (e.g., "Licenciatura", "Mestrado")
 * @property course The specific course or program of study
 * @property studentNumber Unique student identification number
 * @property faesSupport Whether the applicant receives FAES (Emergency Social Support Fund) support
 * @property hasScholarship Whether the applicant has any other scholarships or financial support
 */
data class AcademicInfo(
    val academicDegree: String,
    val course: String,
    val studentNumber: String,
    val faesSupport: Boolean,
    val hasScholarship: Boolean
)

/**
 * Represents a document attached to a scholarship application.
 * 
 * This data class contains information about a supporting document that is
 * required as part of the application process. Documents are stored as Base64
 * encoded strings in Firestore but can be represented as URIs in the UI.
 * 
 * @property id Unique identifier for the document within the application
 * @property name Display name of the document (e.g., "Comprovativo de Inscrição no IPCA")
 * @property uri URI reference to the document file (null when stored in Firestore)
 * @property fileName Original filename of the document (optional)
 */
data class ApplicationDocument(
    val id: Int,
    val name: String,
    val uri: Uri?,
    val fileName: String? = null,
    val base64Data: String? = null // Base64 encoded file data from Firestore
)

/**
 * Enumeration representing the possible statuses of a scholarship application.
 * 
 * Each status represents a different stage in the application review process:
 * - PENDING: Application submitted and awaiting review
 * - UNDER_REVIEW: Application is currently being reviewed
 * - APPROVED: Application has been approved
 * - REJECTED: Application has been rejected
 */
enum class ApplicationStatus(val value: Int) {
    /** Application submitted and awaiting initial review */
    PENDING(0),
    
    /** Application is currently under review by administrators */
    UNDER_REVIEW(1),
    
    /** Application has been approved for scholarship */
    APPROVED(2),
    
    /** Application has been rejected */
    REJECTED(3);
    
    companion object {
        /**
         * Converts an integer value to the corresponding ApplicationStatus enum.
         * 
         * @param value The integer value to convert
         * @return The corresponding ApplicationStatus, or PENDING if value is invalid
         */
        fun fromInt(value: Int?): ApplicationStatus {
            return values().find { it.value == value } ?: PENDING
        }
        
        /**
         * Converts a string value to the corresponding ApplicationStatus enum.
         * This is used for backward compatibility with existing string-based statuses.
         * 
         * @param value The string value to convert
         * @return The corresponding ApplicationStatus, or PENDING if value is invalid
         */
        fun fromString(value: String?): ApplicationStatus {
            return try {
                valueOf(value ?: PENDING.name)
            } catch (e: Exception) {
                PENDING
            }
        }
    }
}

